conf/modules/qc.config
subworkflows/local/qc_aligned_reads.nf
workflows/skierfe.nf

Use BED file when specified, otherwise run with '--by 500'.

Use BED file for mosdepth

---

CHANGELOG.md
modules.json
modules/nf-core/glnexus/environment.yml
modules/nf-core/glnexus/glnexus.diff
modules/nf-core/glnexus/main.nf
modules/nf-core/glnexus/meta.yml

The pipeline failed to fetch the glnexus container from the github container registry. This PR uses the pacbio source of containers and then applies a patch to include the local addition of a bed file.

use pacbio container for glnexus

---

assets/test_data/snp_dbs.csv

Fix local -> GitHub file path.

Fix snp_dbs.csv path

---

modules/local/fqcrs.nf
modules/local/pacbio/hificnv/main.nf
modules/local/sniffles/multisample.nf

Fix modules that doesn't report a version

---

subworkflows/local/utils_nfcore_skierfe_pipeline/main.nf

Remove leftover print

---

.github/workflows/download_pipeline.yml

Update the download pipeline test to the one that will be in the next version of nf-core, based on slack discussion: https://nfcore.slack.com/archives/C04QR0T3G3H/p1712912212013879 
This update adds a try with `nf-core download` without stub if `nf-core download -stub` fails.

update download pipeline test

---

assets/test_data/snp_dbs.csv

No longer used. Test profile pointing to https://raw.githubusercontent.com/genomic-medicine-sweden/test-datasets/nallo/testdata/snp_dbs.csv

Delete assets/test_data directory

---

.github/workflows/download_pipeline.yml

The test can now run without -stub, but runs out of disk space (at the deepvariant step). This PR tries to free up more space on the runner.

Update download pipeline

---

CHANGELOG.md
conf/modules/repeat_calling.config
docs/output.md

Clean up TRGT output directory

---

CHANGELOG.md
bin/split_bed_chunks.py
modules/local/split_bed_chunks/main.nf
subworkflows/local/phasing.nf
subworkflows/local/short_variant_calling.nf
workflows/nallo.nf

This PR adds missing module versions to output, and adds a version to `split_bed_chunks.py`.
Closes #155.

Add missing module versions

---

CHANGELOG.md
assets/methods_description_template.yml

Don't describe the pipeline as part of nf-core

---

.github/workflows/ci.yml
.github/workflows/ci_master.yml
subworkflows/local/qc_aligned_reads.nf

This PR adds a test without a BED-file. This increases the runtime of the test to 50 min, so I'm keeping the bed-file in the test config, and only running it when doing a PR against master.
Closes #136.

Add test without bed

---

CHANGELOG.md
subworkflows/local/call_paralogs.nf

Fix paraphase bgzip

---

.github/ISSUE_TEMPLATE/user_story.yml

Add user story template

---

conf/modules/general.config

samtools cat should not be published

---

.github/workflows/ci.yml
CHANGELOG.md
conf/modules/short_variant_calling.config
nf-test.config
subworkflows/local/short_variant_calling/main.nf
subworkflows/local/short_variant_calling/tests/main.nf.test
subworkflows/local/short_variant_calling/tests/main.nf.test.snap
subworkflows/local/short_variant_calling/tests/nextflow.config
tests/nextflow.config

This PR adds nf-test to the short variant calling workflow and GitHub CI, which will allow for safer refactoring later.
Closes #220

Add nf-test to short variant calling

---

CHANGELOG.md
docs/usage.md
nextflow.config
subworkflows/local/utils_nfcore_nallo_pipeline/main.nf

Rework --preset parameter

---

CHANGELOG.md
conf/modules/short_variant_calling.config
nextflow.config
nextflow_schema.json

Add deepvariant_model_type parameter

---

CHANGELOG.md
workflows/nallo.nf

Don't allow running HiPhase with ONT data

---

.github/workflows/ci.yml
CHANGELOG.md
conf/modules/snv_annotation.config
subworkflows/local/snv_annotation/tests/main.nf.test
subworkflows/local/snv_annotation/tests/main.nf.test.snap

Update VEP annotation

---

CHANGELOG.md
README.md
assets/methods_description_template.yml
conf/test_full.config
modules/local/dipcall.nf
modules/local/whatshap/haplotag/main.nf
subworkflows/local/genome_assembly.nf

This PR removes obsolete TODO statements.

Remove TODOs

---

CHANGELOG.md
workflows/nallo.nf

Allow CNV calling to start as soon as SNV calling for a sample is finished

---

CHANGELOG.md
docs/usage.md
nextflow.config
nextflow_schema.json
subworkflows/local/utils_nfcore_nallo_pipeline/main.nf
workflows/nallo.nf

Add skip for QC aligned reads

---

CHANGELOG.md
docs/usage.md
subworkflows/local/utils_nfcore_nallo_pipeline/main.nf

Changed so that `--reduced_penetrance` and `--score_config_snv` is required by rank variants and not SNV annotation in the parameters check, since that is what they actually are in the workflow.

Fix file requirements

---

.github/workflows/ci.yml
CHANGELOG.md

This PR fixes parallel alignments in CI tests, parameter naming was not changed in hidden files in previous PR. 
Needs #314 to merge.

Fix parallel alignments in CI tests

---

CHANGELOG.md
README.md

Add Zenodo link

---

CHANGELOG.md
conf/modules/call_svs.config
modules/local/add_found_in_tag/environment.yml
modules/local/add_found_in_tag/main.nf
modules/local/add_found_in_tag/tests/main.nf.test
modules/local/add_found_in_tag/tests/main.nf.test.snap
modules/local/add_found_in_tag/tests/tags.yml
subworkflows/local/call_svs/main.nf
subworkflows/local/call_svs/tests/main.nf.test
subworkflows/local/call_svs/tests/main.nf.test.snap
subworkflows/local/call_svs/tests/nextflow.config

This PR adds `;FOUND_IN=${variant_caller}` to INFO in the SV-calling VCFs.
Closes #336.

Add found_in tag to SV calling

---

CHANGELOG.md
conf/modules/general.config
workflows/nallo.nf

This PR closes #362 by adding a bcftools sort after concatenation.

Sort output SNVs

---

CHANGELOG.md
docs/parameters.md
docs/usage.md
nextflow_schema.json

Fix broken links - update schema and docs

---

CHANGELOG.md
docs/usage.md

Update usage.md to change echtvar example

---

CHANGELOG.md
modules.json
modules/nf-core/genmod/annotate/environment.yml
modules/nf-core/genmod/annotate/main.nf
modules/nf-core/genmod/annotate/meta.yml
modules/nf-core/genmod/compound/environment.yml
modules/nf-core/genmod/compound/main.nf
modules/nf-core/genmod/compound/meta.yml
modules/nf-core/genmod/models/environment.yml
modules/nf-core/genmod/models/main.nf
modules/nf-core/genmod/models/meta.yml
modules/nf-core/genmod/score/environment.yml
modules/nf-core/genmod/score/main.nf
modules/nf-core/genmod/score/meta.yml

[Issue #406] Updated genmod to 3.8.3

---

CHANGELOG.md
modules.json
modules/nf-core/longphase/haplotag/main.nf
modules/nf-core/longphase/haplotag/meta.yml
modules/nf-core/longphase/haplotag/tests/main.nf.test.snap
modules/nf-core/longphase/phase/environment.yml
modules/nf-core/longphase/phase/main.nf
modules/nf-core/longphase/phase/meta.yml
modules/nf-core/longphase/phase/tests/main.nf.test.snap

Updated longphase module to most recent version, eliminating superfluous warnings.

[Issue #409] Updated longphase

---

CHANGELOG.md
conf/modules/general.config

Closes #426. Added `--no-RG` switch to minimap so RG tags are not carried over.

Added --no-RG argument to minimap2

---

.github/workflows/build-docs.yml

Adds a workflow to automatically build docs to GitHub Pages.

Add build-docs action

---

CHANGELOG.md
README.md
docs/index.md
docs/output.md
docs/usage.md

Will make https://genomic-medicine-sweden.github.io/nallo really pretty (after merge).
Also clarifies and updates the docs.

Fix and make docs pretty

---

CHANGELOG.md
modules.json
modules/nf-core/svdb/merge/main.nf
modules/nf-core/svdb/merge/meta.yml
modules/nf-core/svdb/merge/tests/main.nf.test
modules/nf-core/svdb/merge/tests/main.nf.test.snap
modules/nf-core/svdb/merge/tests/nextflow.config
subworkflows/local/call_svs/main.nf

This PR updates the SVDB module to sort the input files by name, stablizing the sample order in output files and so the test snapshots.

Update SVDB and fix CALL_SVS tests

---

.github/workflows/ci.yml
CHANGELOG.md
conf/modules/rank_variants.config
modules/local/add_most_severe_consequence.nf
modules/local/add_most_severe_pli.nf
subworkflows/local/annotate_consequence_pli.nf
subworkflows/local/prepare_genome.nf
subworkflows/local/rank_variants/main.nf
subworkflows/local/rank_variants/tests/main.nf.test
subworkflows/local/rank_variants/tests/main.nf.test.snap
subworkflows/local/rank_variants/tests/nextflow.config
workflows/nallo.nf

This PR closes #283. To be able to test rank variants, small refactoring of upstream subworkflows was needed. 
Unfortunately the VEP output is unstable, and the variants can therefore not really be snapshot.

Implement nf-test for rank variants

---

CHANGELOG.md
nextflow.config
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap

lr:hqae is for aligning reads back to an assembly of the same sample, and might not be optimal for aligning to hg38.

minimap2 preset for pacbio should be map-hifi

---

CHANGELOG.md
modules.json
modules/nf-core/genmod/annotate/environment.yml
modules/nf-core/genmod/annotate/main.nf
modules/nf-core/genmod/annotate/tests/main.nf.test
modules/nf-core/genmod/annotate/tests/main.nf.test.snap
modules/nf-core/genmod/compound/environment.yml
modules/nf-core/genmod/compound/main.nf
modules/nf-core/genmod/compound/tests/main.nf.test
modules/nf-core/genmod/compound/tests/main.nf.test.snap
modules/nf-core/genmod/models/environment.yml
modules/nf-core/genmod/models/main.nf
modules/nf-core/genmod/models/tests/main.nf.test
modules/nf-core/genmod/models/tests/main.nf.test.snap
modules/nf-core/genmod/score/environment.yml
modules/nf-core/genmod/score/main.nf
modules/nf-core/genmod/score/tests/main.nf.test
modules/nf-core/genmod/score/tests/main.nf.test.snap
subworkflows/local/rank_variants/tests/main.nf.test.snap
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap
tests/samplesheet_multisample_ont_bam.nf.test.snap

Update genmod to fix models

---

CHANGELOG.md
conf/modules/short_variant_calling.config
docs/output.md
modules.json
modules/nf-core/deepvariant/vcfstatsreport/main.nf
modules/nf-core/deepvariant/vcfstatsreport/meta.yml
modules/nf-core/deepvariant/vcfstatsreport/tests/main.nf.test
modules/nf-core/deepvariant/vcfstatsreport/tests/main.nf.test.snap
modules/nf-core/deepvariant/vcfstatsreport/tests/tags.yml
subworkflows/local/short_variant_calling/main.nf
subworkflows/local/short_variant_calling/tests/main.nf.test.snap
tests/.nftignore
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap
tests/samplesheet_multisample_ont_bam.nf.test.snap

Add deepvariant_vcfstatsreport

---

CHANGELOG.md
workflows/nallo.nf

Closes #455, #453. 
I think these bugs _should_ be able to be caught in a stub test, but there as still modules missing stubs so the pipeline can't run with -stub. Adding issues to track: https://github.com/genomic-medicine-sweden/nallo/issues/472, https://github.com/genomic-medicine-sweden/nallo/issues/473

Fix reference channels

---

.github/workflows/ci.yml
CHANGELOG.md

This should have the same functionality, but fix the failures in CI that happens _after_ merging the PR.

Fix CI not passing after merge

---

CHANGELOG.md
README.md

Fix broken link in README.md

---

CHANGELOG.md
conf/modules/call_cnvs.config
conf/modules/filter_variants.config
conf/modules/general.config
docs/output.md
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap
tests/samplesheet_multisample_ont_bam.nf.test.snap

Missed these two in #502.
Also some output files were named `snv`, and some `snvs`. Change all to `snvs` to match `svs`, `cnvs`, `repeats`.

Change missed `single_sample` and `multi_sample` output directories

---

CHANGELOG.md
workflows/nallo.nf

Add `.collect()` to allow filtering more than one family per run. 

---

CHANGELOG.md
README.md

Add credits

---

CHANGELOG.md
modules.json
modules/nf-core/deepvariant/rundeepvariant/main.nf
modules/nf-core/deepvariant/rundeepvariant/tests/main.nf.test.snap
modules/nf-core/deepvariant/vcfstatsreport/main.nf
modules/nf-core/deepvariant/vcfstatsreport/tests/main.nf.test.snap
subworkflows/local/methylation/tests/main.nf.test.snap
subworkflows/local/short_variant_calling/tests/main.nf.test.snap
subworkflows/local/snv_annotation/tests/main.nf.test.snap
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap
tests/samplesheet_multisample_ont_bam.nf.test.snap

Update DeepVariant version to 1.8.0

---

.nf-core.yml
CHANGELOG.md
nextflow.config
ro-crate-metadata.json

Template sync 3.1.2

---

CHANGELOG.md
docs/output.md

Fix naming mistakes in output docs

---

.github/workflows/download_pipeline.yml
.github/workflows/linting_comment.yml
.nf-core.yml
.pre-commit-config.yaml
CHANGELOG.md

Template update to v3.2.0

---

CHANGELOG.md
workflows/nallo.nf

Fix filter SNVs tries to run even with --skip_snv_calling

---

CHANGELOG.md
conf/modules/call_svs.config
subworkflows/local/call_svs/main.nf
subworkflows/local/call_svs/tests/main.nf.test.snap
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap
tests/samplesheet_multisample_ont_bam.nf.test
tests/samplesheet_multisample_ont_bam.nf.test.snap

Fix unsorted sniffles1 variants

---

CHANGELOG.md
subworkflows/local/utils_nfcore_nallo_pipeline/main.nf

Closes #582. Previous validation was not working.

Fix project samplesheet validation

---

CHANGELOG.md
docs/usage.md

Fix mistake in usage docs

---

CHANGELOG.md
modules.json
modules/nf-core/samtools/fastq/main.nf
modules/nf-core/samtools/fastq/tests/main.nf.test
modules/nf-core/samtools/fastq/tests/main.nf.test.snap

Update samtools/fastq to add stub

---

CHANGELOG.md
modules/local/build_intervals/main.nf

Add stub to `BUILD_INTERVALS`

---

CHANGELOG.md
subworkflows/local/align_assemblies/main.nf
subworkflows/local/annotate_cadd/main.nf
subworkflows/local/bam_infer_sex.nf
subworkflows/local/call_paralogs.nf
subworkflows/local/call_repeat_expansions/main.nf
subworkflows/local/call_svs/main.nf
subworkflows/local/genome_assembly.nf
subworkflows/local/phasing.nf
subworkflows/local/rank_variants/main.nf
subworkflows/local/short_variant_calling/main.nf
workflows/nallo.nf

Update joins with `failOnMismatch:true` & `failOnDuplicate:true`

---

CHANGELOG.md
docs/usage.md

Add runtime estimates

---

CHANGELOG.md
modules.json
modules/local/yak.nf
modules/nf-core/gunzip/main.nf
modules/nf-core/splitubam/environment.yml
modules/nf-core/splitubam/main.nf
modules/nf-core/splitubam/tests/main.nf.test.snap

Closes #610, one step closer to -stub run.

Add stub to yak and update splitubam

---

CHANGELOG.md
subworkflows/local/annotate_svs/tests/main.nf.test
subworkflows/local/methylation/tests/main.nf.test
subworkflows/local/rank_variants/tests/main.nf.test
subworkflows/local/snv_annotation/tests/main.nf.test

Fix paths in tests affected by [#626](https://github.com/genomic-medicine-sweden/nallo/pull/626)

Fix test paths

---

CHANGELOG.md
modules.json
modules/nf-core/fastqc/environment.yml
modules/nf-core/fastqc/main.nf

Updated FastQC module with bugfix from nf-core (see https://github.com/nf-core/modules/pull/8180 ).
NO Update to FastQC itself.

Updated FastQC module

---

CHANGELOG.md
docs/output.md
modules/local/whatshap/stats/main.nf
tests/samplesheet.nf.test.snap
tests/samplesheet_multisample_bam.nf.test.snap
tests/samplesheet_multisample_ont_bam.nf.test.snap

Merge patch to dev

---

CHANGELOG.md
conf/modules/annotate_svs.config
conf/modules/snv_annotation.config

Increase default VEP `max_sv_size`

---

CHANGELOG.md
modules/nf-core/ensemblvep/vep/ensemblvep-vep.diff
modules/nf-core/ensemblvep/vep/main.nf

Reapply VEP 110 patch for singularity

---

CHANGELOG.md
subworkflows/local/snv_annotation/tests/main.nf.test
subworkflows/local/snv_annotation/tests/main.nf.test.snap

Fix nf-test adding md5 to meta.id in SNV_ANNOTATION

---

CHANGELOG.md
modules.json
modules/nf-core/bcftools/norm/main.nf
modules/nf-core/somalier/relate/main.nf
modules/nf-core/somalier/relate/somalier-relate.diff

This PR contains the last items to successfully run the pipeline in `-stub` mode, meaning we can expand the testing. 
Closes #459.

Working stub run

---

.github/workflows/ci.yml
CHANGELOG.md
subworkflows/local/annotate_cadd/tests/main.nf.test
subworkflows/local/annotate_cadd/tests/main.nf.test.snap
subworkflows/local/annotate_cadd/tests/nextflow.config

This PR adds tests for `ANNOTATE_CADD`. Just a stub test, since there's no test references. Closes #463

Add nf-test for annotate_cadd

---

CHANGELOG.md
tests/samplesheet_stub.nf.test
tests/samplesheet_stub.nf.test.snap

Add VEP stub test with mock uncompressed cache

---

CHANGELOG.md
conf/modules/prepare_references.config
subworkflows/local/prepare_references/main.nf
subworkflows/local/prepare_references/tests/main.nf.test
subworkflows/local/prepare_references/tests/main.nf.test.snap
subworkflows/local/prepare_references/tests/nextflow.config

Add nf-test for prepare references

---

CHANGELOG.md
subworkflows/local/qc_aligned_reads/main.nf
subworkflows/local/qc_aligned_reads/tests/main.nf.test
subworkflows/local/qc_aligned_reads/tests/main.nf.test.snap

Add nf-test for QC aligned reads

---

CHANGELOG.md
subworkflows/local/utils_nfcore_nallo_pipeline/main.nf

- **Added warning to validatePacBioLicense**
- **Fixed logging and removed Paraphase**
Fixes #497

Added warnings about PacBio Licenses

---

CHANGELOG.md
docs/parameters.md
nextflow_schema.json

Docs : `hifiasm_preset` set based on `preset` not `profile`
