genomic-medicine-sweden/nallo

- CHANGELOG.md
- nextflow.config
- nextflow_schema.json
- workflows/skierfe.nf
When merging the template update, checking whether input files exist was removed, also the `fromSamplesheet` function. Adding that back in this PR.
> Fix checking whether input files exist

- CHANGELOG.md
- workflows/skierfe.nf
Changed the input channel for mosdepth, so it can run with/without a bed file
> Fixed mosdepth input channel bug when bedfile is not provided

- conf/modules/snv_annotation.config
Full size test fails because only `BCFTOOLS_NORM_SINGLESAMPLE` and not `BCFTOOLS_NORM` was actually decomposing variants. 
This is not caught in the small test profile, I guess because it does not contain variants that need decomposing.
> Update BCFTOOLS_NORM config

- CHANGELOG.md
- modules/local/whatshap/stats/main.nf
Already updated whatshap phase & whatshap haplotag but forgot whatshap stats.
A mulled container will be added in a later release.
> Update whatshap stats version to avoid ZeroDivisionError

- CHANGELOG.md
- workflows/nallo.nf
This is not an ideal solution (performance and disk usage wise), but needs to be fixed before a release. Otherwise, only one of the file is included in the MultiQC report. 
Closes #211
> Merge fastq files before raw read qc

- CHANGELOG.md
- docs/usage.md
- nextflow.config
- nextflow_schema.json
- subworkflows/local/short_variant_calling/main.nf
- subworkflows/local/short_variant_calling/tests/main.nf.test
- subworkflows/local/short_variant_calling/tests/main.nf.test.snap
- workflows/nallo.nf
> Remove --extra_gvcfs

- CHANGELOG.md
- conf/modules/methylation.config
- subworkflows/local/methylation.nf
Fixes
```
WARN: A process with name 'MODKIT_PILEUP_HAPLOTYPES' is defined more than once in module script: /home/runner/work/nallo/nallo/./workflows/../subworkflows/local/methylation.nf -- Make sure to not define the same function as process
```
> Fix linting warning

- CHANGELOG.md
- conf/modules/general.config
- conf/modules/rank_variants.config
- conf/test.config
- tests/main.nf.test
- workflows/nallo.nf
Ranking a VEP annotated VCF with 12 samples and 13M variants used >200GB RAM. This PR reduced that to 20-25 GB.
Since the pipeline doesn't split chromosomes into multiple regions, genmod should be ok to run per chromosome/contig. 
Genmod doesn't allow empty VCF files though. In the testdata region 2.bed contains only RefCall variants, so `--parallel_snv` needs to be reduced to 2, or testdata updated.
Closes #275
> Rank variants in parallel

- CHANGELOG.md
- conf/modules/bam_infer_sex.config
- subworkflows/local/bam_infer_sex.nf
- workflows/nallo.nf
Closes #290 by adding a second somalier relate which is run per sample, on samples with unknown sex. 
This allows variant calling to start right away after alignment and sex check, rather than having to wait for all samples to finish.
> Remove sex check bottleneck 

- CHANGELOG.md
- conf/modules/call_repeat_expansions.config
- modules/local/trgt/main.nf
- subworkflows/local/call_repeat_expansions/main.nf
- tests/main.nf.test.snap
This PR changes the name in the output VCF to `meta.id` instead of taking it from the BAM-file (e.g. changing the sample name from HG002_phased to just HG002). This is required for scout to accept uploads. The `--sample-name` parameter was added in TRGT 0.7.0 and as such an update is needed. 
The TRGT update also requires updating the test-data repeats file (https://github.com/genomic-medicine-sweden/test-datasets/pull/13), as regions in the repeats BED that do not exist in the BAM file/reference now results in errors.
> Add sample name to TRGT output

- CHANGELOG.md
Closes #327 by removing VEP plugins in https://github.com/genomic-medicine-sweden/test-datasets/pull/15 and https://github.com/genomic-medicine-sweden/test-datasets/pull/16.
This PR checks that no snapshots have changed.
> Remove VEP plugins from test-data

- CHANGELOG.md
- conf/test.config
- nextflow.config
- nextflow_schema.json
- subworkflows/local/snv_annotation/tests/main.nf.test
- tests/main.nf.test
- tests/nextflow.config
Fixes #395 by pinning the testdata to how the data looked at the date of the release, otherwise it gets overwritten by developments in dev, and no longer works. 
I had to create a specific test-data branch (nallo-0.3.2) for this release, but in the future I think I should be able to just use the latest test-data commit before the release.
> Patch release 0.3.2

- .github/workflows/ci.yml
- CHANGELOG.md
- modules/local/trgt/main.nf
- subworkflows/local/call_repeat_expansions/main.nf
- subworkflows/local/call_repeat_expansions/tests/main.nf.test
- subworkflows/local/call_repeat_expansions/tests/main.nf.test.snap
- subworkflows/local/call_repeat_expansions/tests/nextflow.config
- tests/samplesheet.nf.test.snap
- tests/samplesheet_multisample_bam.nf.test.snap
- workflows/nallo.nf
> Add found_in tag and nf-test to call repeat expansions

- CHANGELOG.md
- conf/modules/rank_variants.config
- subworkflows/local/rank_variants/main.nf
- subworkflows/local/rank_variants/tests/main.nf.test.snap
- subworkflows/local/rank_variants/tests/nextflow.config
Closes #457. This is really a genmod problem, but adding a bcftools sort to the rank variants subworkflow solves it temporarily. When genmod has been updated, bcftools sort should be removed.
> Fix rank SVs

- .github/workflows/ci.yml
- CHANGELOG.md
- subworkflows/local/annotate_svs/main.nf
This PR incorporates the `changed-since` command in the CI-tests, fixed in nf-test 0.9.2. This makes tests run only if changes have been made in that test.
One thing further would be to skip the tags completely and rely on shards, but there's no easy way to see which tests are run in a shard yet, so I will leave this to another PR.
> nf-test with changed-since

- .github/workflows/keep_a_changelog.yml
- CHANGELOG.md
> Add keep a changelog enforcer

- CHANGELOG.md
- conf/modules/call_svs.config
- conf/modules/general.config
- docs/output.md
- samplesheet_multisample_bam_ont.csv
- subworkflows/local/rank_variants/tests/main.nf.test
- subworkflows/local/short_variant_calling/main.nf
- subworkflows/local/short_variant_calling/tests/main.nf.test.snap
- subworkflows/local/snv_annotation/tests/main.nf.test
- subworkflows/local/snv_annotation/tests/main.nf.test.snap
- subworkflows/local/utils_nfcore_nallo_pipeline/main.nf
- tests/samplesheet.nf.test.snap
- tests/samplesheet_multisample_bam.nf.test.snap
- tests/samplesheet_multisample_ont_bam.nf.test.snap
- workflows/nallo.nf
This PR:
-  Annotates and ranks SNVs per family instead of per project. This is because genmod does not support compound scoring with multiple families in the VCF. Someone that still wants annotated variants per sample can run each sample as a separate family. 
- Changes the output documentation and structure to match `sample` and `family` for all variants
- Puts the validating of the samplesheet into functions, and  removed the use of `ifEmpty`. This is because these error messages would always show up when you had an error, even if that error was unrelated.
- Removed support for automatically creating an echvar database with SNVs and INDELs, since this requires all variants to be combined into one VCF. Might add this back into the future. 
- Removes the `containts_affected` logic from …
> Annotate and rank SNVs per family

- CHANGELOG.md
- workflows/nallo.nf
Since  `--filter_variants_hgnc_ids` is not required, it needs to have a default value `Channel.of([])` when the param is not set, for .map to not error.
> Set ch_hgnc_ids default value

- .github/CONTRIBUTING.md
- CHANGELOG.md
- assets/methods_description_template.yml
- assets/software_references.yml
- modules/local/add_found_in_tag/main.nf
- subworkflows/local/call_svs/tests/main.nf.test.snap
- subworkflows/local/short_variant_calling/tests/main.nf.test.snap
- subworkflows/local/utils_nfcore_nallo_pipeline/main.nf
- tests/samplesheet.nf.test.snap
- tests/samplesheet_multisample_bam.nf.test.snap
- tests/samplesheet_multisample_ont_bam.nf.test.snap
- workflows/nallo.nf
This PR adds a `software_references.yml` and uses that together with the tools reported in `ch_versions` to dynamically write the methods description tools and references, depending on how subworkflows are skipped and params set.
This should make the method description easier to maintain when adding or moving around tools and subworkflows. An error will also be produced if a new tool is added without an entry in `software_references.yml`.
Closes #508.
> Dynamically build methods description from ch_versions

- .github/workflows/ci.yml
- CHANGELOG.md
`latest-everything` CI tests failing because new Nextflow update this week. I don't think we need to ensure compatibility with edge releases, so changed to `latest-stable`.
> Run CI tests with latest-stable version of Nextflow

- CHANGELOG.md
- nextflow.config
> Add contributors to `nextflow.config`

- CHANGELOG.md
- bin/clean_sniffles.py
- nf-test.config
- subworkflows/local/call_svs/tests/main.nf.test.snap
Closes #579, and fixes another bug in the clean_sniffles.py script where `SVTYPE:DUP/INS` should be `SVTYPE=DUP/INS`.
I also realised that some nf-test triggers were missing, e.g. if you modify `nextflow.config` then all tests should be run. I also added the bin directory to that list.
> Fix sniffles1

- CHANGELOG.md
- docs/index.md
- modules/local/split_bed_chunks/main.nf
- nextflow.config
> Review comments

- CHANGELOG.md
- modules.json
- modules/local/create_pedigree_file/main.nf
- modules/local/create_pedigree_file/tests/main.nf.test
- modules/local/echtvar/anno/main.nf
- modules/local/hiphase/main.nf
- modules/nf-core/bcftools/view/environment.yml
- modules/nf-core/bcftools/view/main.nf
- modules/nf-core/longphase/phase/environment.yml
- modules/nf-core/longphase/phase/main.nf
- modules/nf-core/samtools/view/environment.yml
- modules/nf-core/samtools/view/main.nf
- modules/nf-core/svdb/merge/environment.yml
- modules/nf-core/svdb/merge/main.nf
gfastats is left to fix within nf-core, but need some help there.
> Module language server fixes

- CHANGELOG.md
- conf/modules/nallo.config
- subworkflows/local/phasing/main.nf
- tests/samplesheet_multisample_bam.nf.test.snap
- workflows/nallo.nf
This PR changes to only run CRAM conversion for unphased reads when not phasing reads. Since unphased reads are not output when phasing (instead the phased reads are converted and output), running this process is unnecessary.
> Skip unneccessary CRAM conversion
